export { default as About } from './About/About'
export { default as Dashboard } from './Dashboard'
export { default as NotFound } from './NotFound/NotFound'
export { default as Orders } from './Orders'
export { default as Payments } from './Payments'
export { default as ProductAnalytics } from './Product/Analytics'
export { default as Users } from './Users'
